//
//  OSAIUser.h
//  OsaiTableTennisSDK
//
//  Created by Роман Зенченко on 15.09.2021.
//

#import <Foundation/Foundation.h>

@interface OSAIUser : NSObject

/// User was autogenerated, and need to register manually. Only for OSAI Mobile App
@property (assign, nonatomic, readonly) BOOL isAutogeneratedUser;

/// User identifier
@property (strong, nonatomic, readonly) NSNumber *userId;
/// User login
@property (strong, nonatomic, readonly) NSString *userLogin;
/// User password
@property (strong, nonatomic, readonly) NSString *password;
/// User api token
@property (strong, nonatomic, readonly) NSString *token;

/// First name
@property (strong, nonatomic, readonly) NSString *firstName;
/// Last name
@property (strong, nonatomic, readonly) NSString *lastName;

@end
